### ISSUE TITLE
Dúvida sobre Link

### ISSUE THREAD

**Issue by alfredodelfabro** [glaucocustodio/remote_bootstrap_modal#1]
Olá, gostaria de saber se existe a possibilidade de carregar um layout de edição. Por exemplo:

`<%= link_to 'EDITAR', edit_client_path(@client), class: 'btn btn-primary btn-block', data: { modal: true } %>`

Para o new_client_path eu consegui:

<%= link_to 'CADASTRAR', new_client_path, class: 'btn btn-primary btn-block', data: { modal: true } %>

O clients_controller:

```
before_action :set_client, only: [:show, :edit, :update, :destroy]

def new
    @client = Client.new
    @client.build_user
    # Adiciona suporte a adição via modal
    respond_modal_with @client
end

def edit
    respond_modal_with @client, location: edit_client_path
end

def set_client
    @client = Client.find(params[:id])
end
```
Teria ideia do que pode estar ocorrendo, ou poderia ajudar com um exemplo para o caso de abrir um modal para editar um formulário?

**Comment by glaucocustodio** [comment]
Seu código deveria funcionar. O que está acontecendo?

**Comment by alfredodelfabro** [comment]
Opa, agora fiz funcionar corretamente. Na verdade fiz tanta coisa já que não sei o que de fato fez funcionar. Se eu descobrir, fazendo em um outro que preciso, posto aqui. Obrigado!
